'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

test('half-day holidays persist, can be edited and feed attendance and absence flagging', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wln-half-holiday-'));
  process.env.DB_PATH = path.join(dir, 'portal.db');
  process.env.NODE_ENV = 'test'; process.env.JWT_SECRET = 'holiday-test-only';
  delete process.env.ASANA_TOKEN;
  const Database = require('better-sqlite3');
  const legacy = new Database(process.env.DB_PATH);
  legacy.exec("CREATE TABLE holidays(id INTEGER PRIMARY KEY,date TEXT UNIQUE,name TEXT,type TEXT,created_by INTEGER,created_ts INTEGER); INSERT INTO holidays VALUES(1,'2026-01-01','Existing','PUBLIC',NULL,0)");
  legacy.close();
  const express = require('express'); const listen = express.application.listen; let app;
  express.application.listen = function () { app = this; };
  try { require('../src/server'); } finally { express.application.listen = listen; }
  const { db } = require('../src/db'); const { COOKIE, issueToken } = require('../src/auth');
  const admin = db.prepare("SELECT * FROM users WHERE role='ADMIN'").get();
  const empId = db.prepare("INSERT INTO users(name,email,password_hash,role,created_ts) VALUES('Test person','half@example.test','unused','EMPLOYEE',0)").run().lastInsertRowid;
  db.prepare("UPDATE users SET join_date='2026-01-01' WHERE id=?").run(empId);
  const adminCookie = `${COOKIE}=${issueToken(admin)}`;
  const empCookie = `${COOKIE}=${issueToken({ id: empId, role: 'EMPLOYEE' })}`;
  const server = listen.call(app, 0, '127.0.0.1');
  await new Promise((resolve, reject) => { server.once('listening', resolve); server.once('error', reject); });
  t.after(async () => { await new Promise(r => server.close(r)); db.close(); fs.rmSync(dir, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const request = async (url, body, cookie = adminCookie) => {
    const res = await fetch(base + url, { headers: { cookie, 'content-type': 'application/json' }, ...(body ? { method: 'POST', body: JSON.stringify(body) } : {}) });
    return { status: res.status, body: await res.json() };
  };
  assert.equal(db.prepare('SELECT duration FROM holidays WHERE id=1').get().duration, 'FULL');
  assert.equal((await request('/api/holidays', { date: '2026-09-17', name: 'Half holiday', duration: 'HALF' }, empCookie)).status, 403);
  assert.equal((await request('/api/holidays', { date: '2026-02-30', name: 'Invalid', duration: 'HALF' })).status, 400);
  assert.equal((await request('/api/holidays', { date: '2026-09-17', name: 'Invalid', duration: 'QUARTER' })).status, 400);
  assert.equal((await request('/api/holidays', { date: '2026-09-17', name: 'Half holiday', type: 'COMPANY', duration: 'HALF' })).status, 200);
  assert.equal((await request('/api/holidays', null, empCookie)).body.holidays.find(h => h.date === '2026-09-17').duration, 'HALF');
  const report = () => request(`/api/reports/attendance?user_id=${empId}&start=2026-09-17&end=2026-09-17`);
  let r = (await report()).body;
  assert.equal(r.rows[0].status, 'HALF_HOLIDAY_ABSENT'); assert.equal(r.totals.absent, 0.5); assert.equal(r.totals.holiday, 0.5);
  const event = db.prepare('INSERT INTO events(user_id,type,ts,day) VALUES(?,?,?,?)');
  event.run(empId, 'IN', Date.parse('2026-09-16T16:00:00+05:30'), '2026-09-16');
  const { flagAbsences } = require('../src/autoAbsence');
  assert.equal(flagAbsences('2026-09-17'), 1);
  const absence = db.prepare('SELECT * FROM leaves WHERE user_id=?').get(empId);
  assert.equal(absence.kind, 'HALF'); assert.equal(absence.days, 0.5); assert.equal(absence.status, 'PENDING');
  assert.equal(flagAbsences('2026-09-17'), 0);
  event.run(empId, 'IN', Date.parse('2026-09-17T19:00:00+05:30'), '2026-09-17');
  event.run(empId, 'OUT', Date.parse('2026-09-17T23:00:00+05:30'), '2026-09-17');
  r = (await report()).body;
  assert.equal(r.rows[0].status, 'HALF_HOLIDAY_PRESENT'); assert.equal(r.rows[0].short, false); assert.equal(r.rows[0].late, false);
  assert.equal(r.totals.present, 0.5); assert.equal(r.totals.holiday, 0.5); assert.equal(r.totals.workedMinutes, 240);
  const register = (await request('/api/reports/register?month=2026-09')).body;
  assert.equal(register.users.find(u => u.id === empId).cells['2026-09-17'], r.rows[0].status);
  db.prepare("UPDATE leaves SET status='APPROVED' WHERE id=?").run(absence.id);
  r = (await report()).body;
  assert.equal(r.rows[0].status, 'HALF_HOLIDAY_LEAVE'); assert.equal(r.totals.leave, 0.5); assert.equal(r.totals.present, 0);
  await request('/api/holidays', { date: '2026-09-17', name: 'Full holiday', duration: 'FULL' });
  assert.equal(db.prepare("SELECT COUNT(*) AS n FROM holidays WHERE date='2026-09-17'").get().n, 1);
  assert.equal(db.prepare("SELECT duration FROM holidays WHERE date='2026-09-17'").get().duration, 'FULL');
  const restart = spawnSync(process.execPath, ['-e', "const {db}=require('./src/db'); db.close()"], { cwd: path.join(__dirname, '..'), env: process.env, encoding: 'utf8' });
  assert.equal(restart.status, 0, restart.stderr);
});
